/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Graphene;

import Axis.Axis;


/**
 *
 * @author luxformel
 */
public class AxisConfigFrame extends javax.swing.JFrame {

    /**
     * Creates new form AxisConfigFrame
     */
    public AxisConfigFrame() {
        initComponents();
        numbersCheckBox.setSelected(Axis.getDisplayNumbers());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        axisButtonGroup = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        startSpinnerX = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        endSpinnerX = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        startSpinnerY = new javax.swing.JSpinner();
        endSpinnerY = new javax.swing.JSpinner();
        jApplyAxisConfigButton = new javax.swing.JButton();
        jNormalRadioButton = new javax.swing.JRadioButton();
        jUpRadioButton = new javax.swing.JRadioButton();
        jDownRadioButton = new javax.swing.JRadioButton();
        numbersCheckBox = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Configure Your axis:");

        jLabel2.setText("Starting x coordinate:");

        jLabel3.setText("End x coordinate:");

        jLabel4.setText("Starting y-coordinate");

        jLabel5.setText("Ending y-coordinate");

        jApplyAxisConfigButton.setText("Apply");
        jApplyAxisConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jApplyAxisConfigButtonActionPerformed(evt);
            }
        });

        axisButtonGroup.add(jNormalRadioButton);
        jNormalRadioButton.setSelected(true);
        jNormalRadioButton.setText("Normal");

        axisButtonGroup.add(jUpRadioButton);
        jUpRadioButton.setText("Up");

        axisButtonGroup.add(jDownRadioButton);
        jDownRadioButton.setText("Down");

        numbersCheckBox.setSelected(true);
        numbersCheckBox.setText("Display Numbers");
        numbersCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(startSpinnerY, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(startSpinnerX, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(endSpinnerX, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNormalRadioButton)
                        .addGap(28, 28, 28)
                        .addComponent(numbersCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jUpRadioButton)
                    .addComponent(jDownRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jApplyAxisConfigButton, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endSpinnerY, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startSpinnerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endSpinnerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startSpinnerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endSpinnerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNormalRadioButton)
                    .addComponent(numbersCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUpRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDownRadioButton)
                .addGap(18, 18, 18)
                .addComponent(jApplyAxisConfigButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private ApplyListener applyListener;

    public void setApplyListener(ApplyListener listener) {
        this.applyListener = listener;
    }
    
    
    private void jApplyAxisConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jApplyAxisConfigButtonActionPerformed
        // TODO add your handling code here:
        
        //gets X 
        
        int startX = (int) startSpinnerX.getValue();
        int endX = (int)endSpinnerX.getValue();
        
        //gets Y
        
        int startY = (int) startSpinnerY.getValue();
        int endY = (int)endSpinnerY.getValue();
        
        
        // sets if numbers are displayed or not
        
        boolean displayNumbers = numbersCheckBox.isSelected();
        Axis.setDisplayNumbers(displayNumbers);
        
        if (startX != 0 && endX != 0 && startY != 0 && endY != 0) {
            // sets X
            Axis.setStartX(startX);
            Axis.setEndX(endX);
            Axis.calculateXDistance();

            // sets Y 
            Axis.setStartY(startY);
            Axis.setEndY(endY);
            Axis.calculateYDistance();
            
            

        
            // draws the appropriate Axis
            if (jDownRadioButton.isSelected()) {
                Axis.setTypOfAxis("Down");
            }else if (jUpRadioButton.isSelected()) {
                Axis.setTypOfAxis("Up");
            }else if (jNormalRadioButton.isSelected()) {
                Axis.setTypOfAxis("Normal");
            }
            
            
            
        }
        if (applyListener != null) {
                ApplyEvent event = new ApplyEvent(this);
                applyListener.applyButtonClicked(event);
            }
        this.dispose(); // Close the ApplyFrame after applying changes
    }//GEN-LAST:event_jApplyAxisConfigButtonActionPerformed

    private void numbersCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbersCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numbersCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup axisButtonGroup;
    private javax.swing.JSpinner endSpinnerX;
    private javax.swing.JSpinner endSpinnerY;
    private javax.swing.JButton jApplyAxisConfigButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JRadioButton jDownRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jNormalRadioButton;
    private javax.swing.JRadioButton jUpRadioButton;
    private javax.swing.JCheckBox numbersCheckBox;
    private javax.swing.JSpinner startSpinnerX;
    private javax.swing.JSpinner startSpinnerY;
    // End of variables declaration//GEN-END:variables
}
