/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Graphene;

import Axis.Axis;

/**
 *
 * @author luxformel
 */
public class AxisConfigFrame extends javax.swing.JFrame {

    /**
     * Creates new form AxisConfigFrame
     */
    public AxisConfigFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        axisButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        startSpinnerX = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        endSpinnerX = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        startSpinnerY = new javax.swing.JSpinner();
        endSpinnerY = new javax.swing.JSpinner();
        jApplyAxisConfigButton = new javax.swing.JButton();
        jNormalRadioButton = new javax.swing.JRadioButton();
        jUpRadioButton = new javax.swing.JRadioButton();
        jDownRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Configure Your axis:");

        jLabel2.setText("Starting x coordinate:");

        jLabel3.setText("End x coordinate:");

        jLabel4.setText("Starting y-coordinate");

        jLabel5.setText("Ending y-coordinate");

        jApplyAxisConfigButton.setText("Apply");
        jApplyAxisConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jApplyAxisConfigButtonActionPerformed(evt);
            }
        });

        axisButtonGroup.add(jNormalRadioButton);
        jNormalRadioButton.setText("Normal");

        axisButtonGroup.add(jUpRadioButton);
        jUpRadioButton.setText("Up");

        axisButtonGroup.add(jDownRadioButton);
        jDownRadioButton.setText("Down");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jApplyAxisConfigButton, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(startSpinnerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(startSpinnerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endSpinnerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(endSpinnerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jNormalRadioButton)
                    .addComponent(jUpRadioButton)
                    .addComponent(jDownRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startSpinnerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endSpinnerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startSpinnerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endSpinnerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jNormalRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUpRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDownRadioButton)
                .addGap(7, 7, 7)
                .addComponent(jApplyAxisConfigButton)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jApplyAxisConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jApplyAxisConfigButtonActionPerformed
        // TODO add your handling code here:
        // sets X
        Axis.setStartX((int)startSpinnerX.getValue());
        Axis.setEndX((int)endSpinnerX.getValue());
        Axis.calculateXDistance();
        
        // sets Y 
        Axis.setStartY((int)startSpinnerY.getValue());
        Axis.setEndY((int)endSpinnerY.getValue());
        Axis.calculateYDistance();
        
        // draws the appropriate Axis
        if (jDownRadioButton.isSelected()) {
            Axis.setTypOfAxis("Down");
        }else if (jUpRadioButton.isSelected()) {
            Axis.setTypOfAxis("Up");
        }else if (jNormalRadioButton.isSelected()) {
            Axis.setTypOfAxis("Normal");
        }
        //drawPanel.repaint();
    }//GEN-LAST:event_jApplyAxisConfigButtonActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup axisButtonGroup;
    private javax.swing.JSpinner endSpinnerX;
    private javax.swing.JSpinner endSpinnerY;
    private javax.swing.JButton jApplyAxisConfigButton;
    private javax.swing.JRadioButton jDownRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jNormalRadioButton;
    private javax.swing.JRadioButton jUpRadioButton;
    private javax.swing.JSpinner startSpinnerX;
    private javax.swing.JSpinner startSpinnerY;
    // End of variables declaration//GEN-END:variables
}
