/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Graphene;

import Axis.AxisPoints;
import Functions.Function;
import Functions.Functions;
import Line.Lines;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author luxformel
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    private AxisPoints axisPoints;
    private Functions functions = new Functions();
    
    public MainFrame() {
        initComponents();
        loadComboBox();
        functionTextField.setText("");
        
        drawPanel.setAxisPoints(axisPoints);
        drawPanel.setFunctions(functions);
        
        functionsList.setListData(functions.toArray());
        
        System.out.println("width: " + drawPanel.getWidth());
        System.out.println("height: " + drawPanel.getHeight());
        //drawPanel.setTypeOfAxis("NormalDown");
        repaint();
    }
    
    public void updateView(){
        drawPanel.setAxisPoints(axisPoints);
        drawPanel.setFunctions(functions);
        functionsList.setListData(functions.toArray());
               
        repaint();
    }
    
    
    public void loadComboBox(){
        UIManager.LookAndFeelInfo[] lafInfo = UIManager.getInstalledLookAndFeels();
        
        String name;
        String[] names = new String[lafInfo.length];
        for (int i = 0; i < lafInfo.length; i++) {
            name = lafInfo[i].getName();
            names[i] = name;
            System.out.println(name);
        }
        jThemeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(names));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        axisButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        functionButton = new javax.swing.JButton();
        functionTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        drawPanel = new Graphene.DrawPanel();
        jLabel8 = new javax.swing.JLabel();
        jThemeComboBox = new javax.swing.JComboBox<>();
        drawPointsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        functionsList = new javax.swing.JList();
        deleteFunctionButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jExportMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jConfigureAxisMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Graphene");

        functionButton.setText("Show function");
        functionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                functionButtonActionPerformed(evt);
            }
        });

        functionTextField.setText("jTextField1");

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1562, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );

        jLabel8.setText("Select LookAndFeel:");

        jThemeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jThemeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThemeComboBoxActionPerformed(evt);
            }
        });

        drawPointsButton.setText("Draw Points");
        drawPointsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawPointsButtonActionPerformed(evt);
            }
        });

        functionsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(functionsList);

        deleteFunctionButton.setText("Delete function");
        deleteFunctionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFunctionButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Your function:");

        jMenu1.setText("File");

        jExportMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jExportMenuItem.setText("Export");
        jExportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExportMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(jExportMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Axis");

        jConfigureAxisMenuItem.setText("Configure Axis");
        jConfigureAxisMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfigureAxisMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(jConfigureAxisMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jThemeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(functionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(functionTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(deleteFunctionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clearButton)
                                            .addComponent(jLabel8)
                                            .addComponent(drawPointsButton)
                                            .addComponent(jLabel2))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(157, 157, 157)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(drawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(functionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(functionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jThemeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(drawPointsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addGap(12, 12, 12)
                        .addComponent(deleteFunctionButton))
                    .addComponent(drawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void functionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_functionButtonActionPerformed
        // TODO add your handling code here:
        AxisPoints.clear();
        String function = functionTextField.getText();
        if (!function.equals("")) {
            functions.add(new Function(function));        
        }
        drawPanel.setDrawLines(true);
        updateView();
       // System.out.println("number of points: " + Points.size());
    }//GEN-LAST:event_functionButtonActionPerformed

    private void jExportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExportMenuItemActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setDialogTitle("Save Your function as .png");
        
        int response = fileChooser.showSaveDialog(null);
        if (response == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            if (selectedFile != null) {
                // Save button clicked without selecting a file
                String fileName = fileChooser.getSelectedFile().getName();
                File newFile = new File(fileChooser.getCurrentDirectory(), fileName);
                System.out.println("New file: " + newFile.getAbsolutePath());
                
                String path = selectedFile.getAbsolutePath() + ".png";
                ImageGenerator.exportAsPNG(drawPanel, path);
            }   
        }
    }//GEN-LAST:event_jExportMenuItemActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        AxisPoints.clear();
        updateView();   
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jThemeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThemeComboBoxActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String lookAndFeelName =  String.valueOf(jThemeComboBox.getSelectedItem());
            if (lookAndFeelName != null) {
                for (UIManager.LookAndFeelInfo info:UIManager.getInstalledLookAndFeels()) {
                    if (lookAndFeelName.equals(info.getName())) {
                        try {
                            UIManager.setLookAndFeel(info.getClassName());
                            SwingUtilities.updateComponentTreeUI(this);
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (InstantiationException ex) {
                            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IllegalAccessException ex) {
                            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (UnsupportedLookAndFeelException ex) {
                            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;
                    }       
                }
            }
    }//GEN-LAST:event_jThemeComboBoxActionPerformed

    private void jConfigureAxisMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfigureAxisMenuItemActionPerformed
        // TODO add your handling code here:
        AxisConfigFrame axisConfigFrame = new AxisConfigFrame();
        axisConfigFrame.show();
        updateView();
    }//GEN-LAST:event_jConfigureAxisMenuItemActionPerformed

    private void drawPointsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawPointsButtonActionPerformed
        // TODO add your handling code here:
        drawPanel.setDrawLines(true);
        updateView();
    }//GEN-LAST:event_drawPointsButtonActionPerformed

    private void deleteFunctionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFunctionButtonActionPerformed
        // TODO add your handling code here:
        int index = functionsList.getSelectedIndex();
        if (index != -1) {
            functions.remove(index);
        }
        updateView();
    }//GEN-LAST:event_deleteFunctionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup axisButtonGroup;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteFunctionButton;
    protected Graphene.DrawPanel drawPanel;
    private javax.swing.JButton drawPointsButton;
    private javax.swing.JButton functionButton;
    private javax.swing.JTextField functionTextField;
    private javax.swing.JList functionsList;
    private javax.swing.JMenuItem jConfigureAxisMenuItem;
    private javax.swing.JMenuItem jExportMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jThemeComboBox;
    // End of variables declaration//GEN-END:variables
}
